name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-tests:
    name: Build and Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish-image:
    runs-on: ubuntu-latest
    needs: build-and-tests
    name: Publish Docker Hub
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username $DOCKER_USER --password-stdin
          mkdir -p ~/.docker
          cat <<EOF > ~/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n $DOCKER_USER:$DOCKER_PASSWORD | base64)"
              }
            },
            "credsStore": "secretservice"
          }
          EOF
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: |
          IMAGE_TAG=wesleycosta/orangotango-reservations:$(date +'%Y%m%d%H%M%S')
          docker build . --file Dockerfile --tag $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Docker Push
        run: |
          docker tag $IMAGE_TAG wesleycosta/orangotango-reservations:latest
          docker push wesleycosta/orangotango-reservations:latest